import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';

export interface ChapterSnapshot {
  id: string;
  title: string;
  content: string;
  order: number;
  word_count: number;
}

export interface CharacterSnapshot {
  id: string;
  name: string;
  description: string;
  personality: string;
  appearance: string;
  background: string;
}

export interface WorldViewSnapshot {
  id: string;
  name: string;
  category: string;
  description: string;
}

export interface PlotPointSnapshot {
  id: string;
  title: string;
  content: string;
  chapter_id: string | null;
  order: number;
}

export interface SnapshotMetadata {
  total_words: number;
  total_chapters: number;
  total_characters: number;
  auto_generated: boolean;
  tags: string[];
}

export interface ProjectSnapshot {
  id: string;
  project_id: string;
  version: string;
  timestamp: number;
  description: string;
  chapters: ChapterSnapshot[];
  characters: CharacterSnapshot[];
  world_views: WorldViewSnapshot[];
  plot_points: PlotPointSnapshot[];
  metadata: SnapshotMetadata;
  auto_generated: boolean;
}

export interface VersionDiff {
  from_version: string;
  to_version: string;
  timestamp: number;
  chapter_changes: Array<{
    id: string;
    action: 'created' | 'modified' | 'deleted';
    changes: Array<{
      position: number;
      removed: string;
      added: string;
    }>;
  }>;
  character_changes: Array<{
    id: string;
    name: string;
    action: 'created' | 'modified' | 'deleted';
    field_changes: Array<{
      field: string;
      old_value: string | null;
      new_value: string | null;
    }>;
  }>;
  world_view_changes: Array<{
    id: string;
    name: string;
    action: 'created' | 'modified' | 'deleted';
    field_changes: Array<{
      field: string;
      old_value: string | null;
      new_value: string | null;
    }>;
  }>;
  plot_point_changes: Array<{
    id: string;
    title: string;
    action: 'created' | 'modified' | 'deleted';
    field_changes: Array<{
      field: string;
      old_value: string | null;
      new_value: string | null;
    }>;
  }>;
}

export interface VersionControlConfig {
  auto_save_enabled: boolean;
  auto_save_interval_minutes: number;
  max_snapshots_per_project: number;
  compression_enabled: boolean;
}

class VersionControlService {
  async createSnapshot(
    projectId: string,
    version: string,
    description: string,
    autoGenerated = false
  ): Promise<ProjectSnapshot> {
    return await invoke<ProjectSnapshot>('create_snapshot', {
      projectId,
      version,
      description,
      autoGenerated,
    });
  }

  async getSnapshots(projectId: string): Promise<ProjectSnapshot[]> {
    return await invoke<ProjectSnapshot[]>('get_snapshots', { projectId });
  }

  async getSnapshot(snapshotId: string): Promise<ProjectSnapshot> {
    return await invoke<ProjectSnapshot>('get_snapshot', { snapshotId });
  }

  async restoreSnapshot(snapshotId: string): Promise<{ status: string }> {
    return await invoke<{ status: string }>('restore_snapshot', { snapshotId });
  }

  async deleteSnapshot(snapshotId: string): Promise<{ status: string }> {
    return await invoke<{ status: string }>('delete_snapshot', { snapshotId });
  }

  async compareSnapshots(
    fromSnapshotId: string,
    toSnapshotId: string
  ): Promise<VersionDiff> {
    return await invoke<VersionDiff>('compare_snapshots', {
      fromSnapshotId,
      toSnapshotId,
    });
  }

  async getVersionConfig(): Promise<VersionControlConfig> {
    return await invoke<VersionControlConfig>('get_version_config');
  }

  async setVersionConfig(config: VersionControlConfig): Promise<{ status: string }> {
    return await invoke<{ status: string }>('set_version_config', {
      configJson: JSON.stringify(config),
    });
  }

  async onSnapshotCreated(callback: (snapshot: ProjectSnapshot) => void) {
    return await listen<ProjectSnapshot>('snapshot-created', (event) => {
      callback(event.payload);
    });
  }

  async onSnapshotRestored(callback: (snapshotId: string) => void) {
    return await listen<string>('snapshot-restored', (event) => {
      callback(event.payload);
    });
  }
}

export const versionControlService = new VersionControlService();
